language: ruby
rvm:
- 2.3.1

install:
  - gem uninstall bundler -x
  - gem install bundler -v "=1.10.6"
  - bundle install

script:
  - bundle exec jekyll build

branches:
  only:
  - master

sudo: false