title: Adam Pajkert - Developer website.
description: My name is Adam Pajkert over the internet known as pajadam.
             Here You can find some basic informations about me and projects
             that I've done in the past. Feel free to check out my blog and
             social media.
altname: Adam Pajkert | pajadam
author: Adam Pajkert
url: "https://pajadam.me"

markdown: kramdown

plugins:
  - jekyll-press

jekyll-press:
  exclude: [ 'sitemap.xml', 'robots.txt' ]
  js_options: {}
  css_options: {}
  html_options: {}

exclude: [ "LICENSE", "README.md", ".gitignore", ".gitattributes", "Gemfile", ".bundle", ".editorconfig" ]
